routes/web.php
<?php

use App\Http\Controllers\BalitaController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\IbuHamilController;
use App\Http\Controllers\ImunisasiController;
use App\Http\Controllers\KematianController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PenimbanganController;
use App\Http\Controllers\VitaminController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::prefix('admin')->middleware('admin')->group(function () {
    Route::get('/', [DashboardController::class, 'index']);
    Route::get('balita', [BalitaController::class, 'index'])->name('balita-index');
    Route::get('balita/detail/{id}', [BalitaController::class, 'show'])->name('balita-show');
    Route::get('balita/hapus/{id}', [BalitaController::class, 'destroy'])->name('balita-destroy');
    Route::get('balita/tambah-data', [BalitaController::class, 'tambah'])->name('balita-tambah-data');
    Route::post('balita/tambah-data', [BalitaController::class, 'store'])->name('balita-tambah-store');
    Route::get('balita/{id}/edit', [BalitaController::class, 'edit'])->name('balita-edit');
    Route::post('balita/{id}/update', [BalitaController::class, 'update'])->name('balita-update');

    Route::get('ibu-hamil', [IbuHamilController::class, 'index'])->name('ibu-hamil-index');
    Route::get('ibu-hamil/detail/{id}', [IbuHamilController::class, 'show'])->name('ibu-hamil-detail');
    Route::get('ibu-hamil/create', [IbuHamilController::class, 'tambah'])->name('ibu-hamil-tambah-data');
    Route::post('ibu-hamil/store-data', [IbuHamilController::class, 'store'])->name('ibu-hamil-store');
    Route::get('ibu-hamil/tambah-edit/{id}', [IbuHamilController::class, 'edit'])->name('ibu-hamil-edit');
    Route::put('ibu-hamil/tambah-update/{id}', [IbuHamilController::class, 'update'])->name('ibu-hamil-update');
    Route::get('ibu-hamil/hapus/{id}', [IbuHamilController::class, 'destroy'])->name('ibu-hamil-hapus');

    Route::resource('penimbangan', PenimbanganController::class);

    Route::resource('imunisasi', ImunisasiController::class);

    Route::resource('vitamin', VitaminController::class);

    Route::resource('kematian', KematianController::class);

    Route::get('laporan', [LaporanController::class, 'index'])->name('laporan');
    Route::get('laporan/balita-print', [LaporanController::class, 'balitaPrint'])->name('laporan-balita');
    Route::get('laporan/ibu-hamil-print', [LaporanController::class, 'ibuHamilPrint'])->name('laporan-ibu-hamil');
    Route::get('laporan/kematian-print', [LaporanController::class, 'kematianPrint'])->name('laporan-kematian');
    Route::get('laporan/imunisasi-print', [LaporanController::class, 'imunisasiPrint'])->name('laporan-imunisasi');
    Route::get('laporan/vitamin-print', [LaporanController::class, 'vitaminPrint'])->name('laporan-vitamin');
    Route::get('laporan/penimbangan-print', [LaporanController::class, 'penimbanganPrint'])->name('laporan-penimbangan');
});

app/Models/Imunisasi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Imunisasi extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function anak(){
        return $this->belongsTo('App\Models\Balita', 'id_anak');
    }
}

app/Http/Controllers/ImunisasiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Balita;
use App\Models\Imunisasi;
use Illuminate\Http\Request;

class ImunisasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $q = $request->q;
        if($q){
            $data = Imunisasi::with('anak')->whereRelation('anak', 'nama_anak', 'LIKE', '%'.$q.'%')
            ->orderBy('id', 'desc')
            ->paginate(10);
        }else{
            $data = Imunisasi::with('anak')
            ->orderBy('id', 'desc')
            ->paginate(10);
        }

        return view('pages.admin.imunisasi.index', [
            'items' => $data,
            'q' => $q
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $anak = Balita::get();

        return view('pages.admin.imunisasi.tambah', [
            'anak' => $anak
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->except(['_token']);
        Imunisasi::create($data);

        return redirect()->route('imunisasi.index')->with('success', 'Berhasil tambah data baru');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Imunisasi::with('anak')->find($id);

        return view('pages.admin.imunisasi.detail', [
            'item' => $data
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $anak = Balita::get();
        $imunisasi = Imunisasi::find($id);

        return view('pages.admin.imunisasi.edit', [
            'anak' => $anak,
            'item' => $imunisasi
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->except(['_token', '_method']);

        $data = Imunisasi::find($id)->update($data);

        return redirect()->route('imunisasi.index')->with('success', 'Berhasil update data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Imunisasi::find($id)->delete();

        return redirect()->back()->with('success', 'Berhasil hapus data');
    }
}

resources/views/pages/admin/imunisasi/detail.blade.php
@extends('layouts.dashboard')

@section('title')
Detail Data
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <label for="">Nama Anak</label>
                <div>
                    <strong>{{ $item->anak->nama_anak }}</strong>
                </div>
                <hr>
            </div>
            <div class="col-md-4">
                <label for="">Tanggal Imunisasi</label>
                <div>
                    <strong>{{ \Carbon\Carbon::parse($item->tanggal_imunisasi)->translatedFormat('l, d F Y')
                        }}</strong>
                </div>
                <hr>
            </div>
            <div class="col-md-4">
                <label for="">Jenis Imunisasi</label>
                <div>
                    <strong>{{ $item->jenis_imunisasi }}</strong>
                </div>
                <hr>
            </div>
            <div class="col-md-4">
                <label for="">Usia</label>
                <div>
                    <strong>{{ $item->usia }} Tahun</strong>
                </div>
                <hr>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/admin/imunisasi/edit.blade.php
@extends('layouts.dashboard')

@section('title')
Edit Data
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <form action="{{ route('imunisasi.update', $item->id) }}" method="post">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-4">
                    <label for="">Nama Anak</label>
                    <select name="id_anak" id="" class="form-select" required>
                        <option value="">Pilih Anak</option>
                        @foreach ($anak as $itemAnak)
                        <option value="{{ $itemAnak->id }}" {{ $itemAnak->id === $item->id_anak ? 'selected' : '' }}>{{
                            $itemAnak->nama_anak }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="">Jenis Imunisasi</label>
                    <select name="jenis_imunisasi" id="" class="form-select" required>
                        <option value="">Pilih Jenis Imunisasi</option>
                        <option value="Hepatitis B" {{ 'Hepatitis B'===$item->jenis_imunisasi ? 'selected' :
                            ''}}>Hepatitis B</option>
                        <option value="Polio" {{ 'Polio'===$item->jenis_imunisasi ? 'selected' :
                            ''}}>Polio</option>
                        <option value="BCG" {{ 'BCG'===$item->jenis_imunisasi ? 'selected' :
                            ''}}>BCG</option>
                        <option value="DPT" {{ 'DPT'===$item->jenis_imunisasi ? 'selected' :
                            ''}}>DPT</option>
                        <option value="Hib" {{ 'Hib'===$item->jenis_imunisasi ? 'selected' :
                            ''}}>Hib</option>
                        <option value="Campak" {{ 'Campak'===$item->jenis_imunisasi ? 'selected' :
                            ''}}>Campak</option>
                        <option value="MMR" {{ 'MMR'===$item->jenis_imunisasi ? 'selected' :
                            ''}}>MMR</option>
                        <option value="PCV" {{ 'PCV'===$item->jenis_imunisasi ? 'selected' :
                            ''}}>PCV</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="">Usia</label>
                    <input required type="number" class="form-control" name="usia" value="{{ $item->usia }}">
                </div>
                <div class="col-md-4">
                    <label for="">Tanggal Pemberian Imunisasi</label>
                    <input required type="date" class="form-control" name="tanggal_imunisasi"
                        value="{{ $item->tanggal_imunisasi }}">
                </div>

                <div class="col-12 mt-4">
                    <button required type="submit" class="btn btn-success">Simpan</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/pages/admin/imunisasi/index.blade.php
@extends('layouts.dashboard')


@section('content')

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col">
                <a href="{{ route('imunisasi.create') }}" class="btn btn-success">Tambah Data</a>
            </div>
            <div class="col">
                <form action="{{ route('imunisasi.index') }}" method="get">
                    <div class="d-flex">
                        <input type="text" class="form-control" placeholder="Cari data" name="q" value="{{ $q }}">
                        <button class="btn btn-info" type="submit">Cari</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover table-sm" style="font-size: 12px;">
                <thead>
                    <tr>
                        <th scope="col">NO</th>
                        <th scope="col">ID IMUNISASI</th>
                        <th scope="col">NAMA ANAK</th>
                        <th scope="col">JENIS IMUNISASI</th>
                        <th scope="col">USIA</th>
                        <th scope="col">TANGGAL IMUNISASI</th>
                        <th>Action</th>
                    </tr>
                </thead>
                @php
                $no = 1;
                @endphp
                <tbody>
                    @forelse ($items as $item)
                    <tr>
                        <th scope="row">{{ $no }}</th>
                        <td>{{ $item->id }}</td>
                        <td>{{ $item->anak->nama_anak }}</td>
                        <td>{{ $item->jenis_imunisasi }}</td>
                        <td>{{ $item->usia }}</td>
                        <td>{{ \Carbon\Carbon::parse($item->tanggal_imunisasi)->translatedFormat('l, d F Y') }}</td>
                        <td class="text-left d-flex justify-content-between" style="">
                            <a href="{{ route('imunisasi.edit', $item->id) }}" class="btn btn-warning btn-sm">Edit</a>
                            <form action="{{ route('imunisasi.destroy', $item->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" onclick="return confirm('Yakin hapus data ini ?')"
                                    class="btn btn-danger btn-sm">Hapus</button>
                            </form>
                            <a href="{{ route('imunisasi.show', $item->id) }}" class="btn btn-info btn-sm">Lihat</a>
                        </td>
                    </tr>
                    @php
                    $no++;
                    @endphp
                    @empty
                    <td colspan="10" class="text-center">
                        <h6>Data Tidak Ada</h6>
                    </td>
                    @endforelse
                </tbody>
            </table>
        </div>
        <div class="d-flex">
            {!! $items->links() !!}
        </div>

    </div>
</div>
@endsection

@push('style')
<style>
    .btn-sm {
        font-size: .775rem !important;
    }
</style>
@endpush

resources/views/pages/admin/imunisasi/tambah.blade.php
@extends('layouts.dashboard')

@section('title')
Tambah Data
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <form action="{{ route('imunisasi.store') }}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-4">
                    <label for="">Nama Anak</label>
                    <select name="id_anak" id="" class="form-select" required>
                        <option value="">Pilih Anak</option>
                        @foreach ($anak as $item)
                        <option value="{{ $item->id }}">{{ $item->nama_anak }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="">Jenis Imunisasi</label>
                    <select name="jenis_imunisasi" id="" class="form-select" required>
                        <option value="">Pilih Jenis Imunisasi</option>
                        <option value="Hepatitis B">Hepatitis B</option>
                        <option value="Polio">Polio</option>
                        <option value="BCG">BCG</option>
                        <option value="DPT">DPT</option>
                        <option value="Hib">Hib</option>
                        <option value="Campak">Campak</option>
                        <option value="MMR">MMR</option>
                        <option value="PCV">PCV</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="">Usia</label>
                    <input required type="number" class="form-control" name="usia">
                </div>
                <div class="col-md-4">
                    <label for="">Tanggal Pemberian Imunisasi</label>
                    <input required type="date" class="form-control" name="tanggal_imunisasi">
                </div>

                <div class="col-12 mt-4">
                    <button required type="submit" class="btn btn-success">Simpan</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection